---
- hosts: all
  become: yes
  remote_user: root 
  roles:
  - nginx_for_nodejs

- hosts: all
  become: yes
  remote_user: root
  roles:
  - nodejs

- hosts: all
  become: yes
  remote_user: root
  roles:
  - postgresql
